### PR TITLE
Run ANALYZE before grounding

### PR DESCRIPTION
**Pull request by alldefector**
see
https://github.com/HazyResearch/deepdive/commit/5fa7493e0c1a73c144ff79f7
5719856d72f7f8cc

### CODE REVIEW

**Comment by netj** [comment]
ANALYZE doesn't work for mysql, see: 4af3a508ca08b0153560f1835d91af18b33b0135

**Comment by alldefector** [comment]
Thanks, Jaeho. Looks like it's getting a bit complicated to backport... Unless develop are going to be merged within a couple days, could you or Feiran patch master with the 5fa7493 change? It'd make grounding 50X faster for current users.

**Comment by chrismre** [comment]
The MYSQL port is broken, and it is likely to remain so for a while. I
would prefer to push this patch, since MySQL is neglected (and was never
recommended...)

**Comment by netj** [comment]
I'll take care of this asap and backport to master.

**Comment by feiranwang** [comment]
I think the commit below might be better. It handles psql/mysql issue https://github.com/HazyResearch/deepdive/commit/0253dd711e403d577814efcab791d92c0ff79577.
Should I put that in?

**Comment by netj** [comment]
I thought I put that in, but maybe not.  You can try that again, but a cursory look at 0253dd7 makes me even more confused: it seems analyzeTable() is returning string, but how is it getting executed?  At least the one I put in called execute().

This combinatorial explosion over the control flow is really a mess and I think we should simply strip the current mysql code and redo it when necessary, possibly in a way that's well isolated from the postgres/greenplum implementation.

**Pull request merged**
