### PR TITLE
fix DISTINCT issue in grounding

### PR DESCRIPTION
**Pull request by SenWu**
Fixed DISTINCT issue mentioned #378

### CODE REVIEW

**Comment by netj** [comment]
Any anticipated side effects if we drop DISTINCT?  I think there must have been a good reason or use case why we added it in the first place.

**Comment by chrismre** [comment]
This makes me really nervous :)

**Comment by alldefector** [comment]
I wasn't able to find who first introduced DISTINCT with git blame because
of some refactoring. Maybe the initial author just has to speak up about
his thought process... Or someone with better git skills could track it
down...

**Comment by chrismre** [comment]
If DISTINCT is not needed, then there has to be some convention somewhere
that ensure DISTINCT is unnecessary. IF you want to remove it, explain what
that convention and make sure it's documented (and ideally checked!)

**Comment by raphaelhoffmann** [comment]
Yes, some more documentation would be helpful here. Here's why I think that DISTINCT is not necessary. Our query is 
https://github.com/HazyResearch/deepdive/blob/master/src/main/scala/org/deepdive/inference/SQLInferenceRunner.scala#L719

*Claim 1: For every tuple in the left table, there is at most one join tuple.*

The join condition is a key for the right table. 

https://github.com/HazyResearch/deepdive/blob/master/src/main/scala/org/deepdive/inference/SQLInferenceRunner.scala#L710
https://github.com/HazyResearch/deepdive/blob/master/src/main/scala/org/deepdive/inference/SQLInferenceRunner.scala#L688
https://github.com/HazyResearch/deepdive/blob/master/src/main/scala/org/deepdive/inference/SQLInferenceRunner.scala#L579

*Claim 2: Each join tuple is distinct.*

The join selects factor_id which is a key for the left table.

https://github.com/HazyResearch/deepdive/blob/master/src/main/scala/org/deepdive/inference/SQLInferenceRunner.scala#L563

**Comment by zhangce** [comment]
@raphaelhoffmann You are right, for the following query

SELECT DISTINCT t0.id AS factor_id, t1.id AS weight_id, "ismassageparlorad.id"
FROM dd_query_f_ismassageparlorad_features t0, dd_weights_f_ismassageparlorad_features t1
WHERE t0."ismassageparlorad.feature" = t1."ismassageparlorad.feature"

The second relation (`dd_weights_f_ismassageparlorad_features`) is grounded by running DISTINCT
over the first relation (`dd_query_f_ismassageparlorad_features`). Therefore, there is no way this query can generate duplicate result.

@SenWu Can you document this in the code?

Ce

**Comment by SenWu** [comment]
@zhangce Yes, I found I add it in our incremental update which it is unnecessary. Sorry about that. Will add specification in the code.

**Comment by SenWu** [comment]
Updated.

**Comment by chrismre** [comment]
@SenWu @zhangce We have some issues failing on the pr... can we figure out the issue here? How robust is the failing incremental test? 

I'm, for example, worried that it would fail on another architecture or with different random draws, etc. Can someone give me some better understanding of this test? (in meeting is fine)

**Comment by feiranwang** [comment]
@chrismre There was a bug introduced by an earlier commit, and it is fixed in #376. The incremental test is stable after merging #376.

**Comment by chrismre** [comment]
sounds good. Thanks for the explanation!

**Pull request merged**
