### PR TITLE
Added dark data banner

### PR DESCRIPTION
**Pull request by zifeishan**
Added a banner image of "dark data".

### CODE REVIEW

**Comment by zifeishan** [comment]
@zhangce Should we merge and deploy this?

**Comment by zhangce** [comment]
I think it looks good.

Ce

**Comment by zifeishan** [comment]
@zhangce Do we want to link this banner to somewhere? Currently it links to nowhere.

**Comment by zhangce** [comment]
>> @zhangce <https://github.com/zhangce> Do we want to link this banner to
somewhere? Currently it links to nowhere.

I think it is OK because it is a general description of DD.

Ce

**Pull request merged**
