### PR TITLE
Added a view dd_feature_statistics for error analysis

### PR DESCRIPTION
**Pull request by zifeishan**
- The view displays all features with correlated pos/neg examples (for
  unary factors only). Looking at this view is a way to determine
  why a specific feature gets high / low weights.
- This view is used by [a new release of BrainDump](https://github.com/zifeishan/braindump/releases/tag/v0.1.2) (it's also backward compatible to previous version of DeepDive).

### CODE REVIEW

**Comment by zifeishan** [comment]
Note that this is a PR to develop branch. This feature can be released later.

@rionda @zhangce @feiranwang Would anyone review my code here? It's mostly changes to grounding. Thanks!

**Comment by rionda** [comment]
This looks good (and very useful), but please document the table name in the apposite document.

**Comment by feiranwang** [comment]
Looks good to me!

**Comment by zifeishan** [comment]
@rionda Docs are updated. Thanks!

**Comment by rionda** [comment]
Ok, @zifeishan , merged.

**Pull request merged**
