### PR TITLE
whitespace cleanup + style check

### PR DESCRIPTION
**Pull request by netj**
After having trouble dealing with whitespace changes from the last release, I decided to add a script that enforces some very basic coding styles and cleanup all the previous mess:
- [no files without eol at the end](http://stackoverflow.com/questions/729692/why-should-files-end-with-a-newline)
- no DOS line endings (CRLF), always use Unix (LF)
- no trailing spaces
- no tabs in indentation (except Makefile, raw data)

Travis will always first check these styles and proceed to the rest of the build and tests.  Developers can run check locally before pushing:

```bash
make checkstyle
```

Let's rebase all our ongoing work on this PR and completely forget about whitespace issues from now on.

### CODE REVIEW

**Comment by netj** [comment]
[Adding w=1 to the diff](https://github.com/HazyResearch/deepdive/pull/328/files?w=1) will show just the script and modification to Makefile and travis.yml.

**Comment by badder** [comment]
This is great! Maybe also add some git hooks to enforce from the client side? Travis takes too long..

**Comment by alldefector** [comment]
This is great! Maybe also add some git hooks to enforce from the client side? Travis takes too long..

E.g.: http://stackoverflow.com/questions/591923/make-git-automatically-remove-trailing-whitespace-before-committing

**Comment by netj** [comment]
I'm reluctant to add it to developer's normal workflow.  Anyone who set up the editor appropriately will never create violations, so I think it's only going to slow down the innocent.  Gatekeeping bad code from Travis for PRs seems enough to me.  Speeding up Travis tests is another thing I'm planning to do in #325.

I made sure one can easily check what's wrong with the make command and open the problematic files from an editor if they ever need to:
```bash
vim $(make checkstyle)
```

I found an [interesting tool to deal with whitespaces from the Q&A](https://github.com/dlenski/wtf).  I guess we should rewrite the checks with it sometime later.  The script I think should eventually be rewritten as another test suite with a proper test framework like [Bats](https://github.com/sstephenson/bats) or so.

**Comment by alldefector** [comment]
I don't really understand the script, but it looks quite legit! How do I approve the PR?

**Comment by netj** [comment]
Thanks for reviewing. There's no formal button for approving PRs. You can just express approval like this and since we're both commiters either of us can press merge! :)

**Pull request merged**
