### PR TITLE
fix bug/doc in open data

### PR DESCRIPTION
**Pull request by zhangce**
@netj These are the version that fixed issues
https://github.com/HazyResearch/deepdive/issues/407
https://github.com/HazyResearch/deepdive/issues/406
https://github.com/HazyResearch/deepdive/issues/405

Sorry for the bug!

Ce

### CODE REVIEW

**Comment by netj** [comment]
Thanks for making these fixes.

I think the dataset README is still confusing to just point to the general walkthrough.  How about pointing to the opendata's "Data Format (NLP Markups)" section and enumerating the list of columns there under the first bullet?  In fact, the opendata TSVs are slightly different from the walkthrough: they have provenance and word index columns, sentence id appears after document id, the dependency paths are represented differently using two columns.  I think these datasets are often consumed/prepared by people who have no idea/interest in what they're processing or how they are actually used in DD, so I think we need to be very precise in describing the exact schema.

**Comment by zhangce** [comment]
Thanks! I will make these changes.

>> I think these datasets are often consumed/prepared by people who have no idea/interest in what they're processing or how they are actually used in DD

I think if the user does not want to use DD to process this data, we do provide the CoNLL format, which is a standard format that user can use.

>> In fact, the opendata TSVs are slightly different from the walkthrough: they have provenance and word index columns, sentence id appears after document id, the dependency paths are represented differently using two columns. 

This might not be a short-term thing, but I feel like we need to change the walkthrough to make it Bazaar-compliant OR make Bazaar walkthrough-compliant. Open data is not the place that we define the schema; Bazaar is the place that we define the schema for both open data and walkthrough to use.

**Comment by zhangce** [comment]
@netj I did another pass.

**Comment by netj** [comment]
Looks great!

On the first point, I meant there may be professional DBAs involved who prepares the database for the actual DD user, who don't necessarily want to follow the details of DD tutorial.  Anyway the new schema page looks great.

I completely agree the tutorial should be updated at one point to include Bazaar and embrace its format.

**Pull request merged**
