### PR TITLE
Update samplers

### PR DESCRIPTION
**Pull request by feiranwang**
As discussed in #238, #258.

### CODE REVIEW

**Comment by netj** [comment]
Could you squash the submodule and binary update into a single commit, with a more descriptive message (what it fixes, why it had to be updated, etc.)?  Maybe even with the doc updates.  That way it's much clearer what those opaque changes are.

**Comment by netj** [comment]
Thanks for squashing.  Should we turn the --sample_evidence flag on by default as suggested?  Is there a test that checks whether the flag works?

**Comment by feiranwang** [comment]
I think it may be better to keep the default behavior as before and give users the option to change, for backward compatibility.
This arg was tested locally. I'll also add a test for this in sampler's tests.

**Comment by feiranwang** [comment]
Test for sample_evidence was added in sampler's develop branch. I utilized the existing test, and add --sample_evidence to it, and checked the results.

**Pull request merged**
