### PR TITLE
Develop fix

### PR DESCRIPTION
**Pull request by feiranwang**
1. fix wrtting back inference result
2. get rid of create table if not exists
3. add more learning epochs to biased coin

### CODE REVIEW

**Comment by feiranwang** [comment]
Also updated distribution key in incremental mode

**Comment by netj** [comment]
For the record, the latest DELETE fix fails on PGXL during incremental test with the following error:
```
+ ./run.sh spouse_example.symmetry.ddl --incremental inference inc.f1+f2+symmetry.out
[...]
10:01:33 [PostgresDataStore(akka://deepdive)] DEBUG Executing query via JDBC: CREATE UNLOGGED TABLE dd_graph_weights (id bigint, isfixed int, initvalue real, cardinality text,
       description text) DISTRIBUTE BY REPLICATION
10:01:33 [PostgresDataStore(akka://deepdive)] DEBUG Executing query via JDBC: DROP SEQUENCE IF EXISTS dd_weight_sequence CASCADE
10:01:33 [PostgresDataStore(akka://deepdive)] DEBUG Executing query via JDBC: CREATE SEQUENCE dd_weight_sequence MINVALUE -1 START 0
10:01:33 [PostgresDataStore(akka://deepdive)] DEBUG Executing query via JDBC: DROP SEQUENCE IF EXISTS dd_factor_sequence CASCADE
10:01:33 [PostgresDataStore(akka://deepdive)] DEBUG Executing query via JDBC: CREATE SEQUENCE dd_factor_sequence MINVALUE -1 START 0
10:01:33 [PostgresDataStore(akka://deepdive)] DEBUG Executing SQL with callback...  SELECT num_weights FROM dd_incremental_meta_data
10:01:33 [PostgresDataStore(akka://deepdive)] DEBUG Executing query via JDBC: ALTER SEQUENCE dd_weight_sequence RESTART 2221
10:01:33 [PostgresDataStore(akka://deepdive)] DEBUG Executing SQL with callback...  SELECT num_factors FROM dd_incremental_meta_data
10:01:33 [PostgresDataStore(akka://deepdive)] DEBUG Executing query via JDBC: ALTER SEQUENCE dd_factor_sequence RESTART 40310
10:01:33 [PostgresDataStore(akka://deepdive)] DEBUG Executing query via JDBC: DROP TABLE IF EXISTS dd_graph_weights CASCADE
10:01:33 [PostgresDataStore(akka://deepdive)] DEBUG Executing SQL with callback... SELECT version() LIKE '%Postgres-XL%';
10:01:33 [PostgresDataStore(akka://deepdive)] DEBUG Executing query via JDBC: CREATE UNLOGGED TABLE dd_graph_weights (id bigint, isfixed int, initvalue real, cardinality text,
     description text)
10:01:33 [PostgresDataStore(akka://deepdive)] DEBUG Executing query via JDBC: DROP TABLE IF EXISTS dd_query_dd_new_has_spouse_0 CASCADE
10:01:33 [PostgresDataStore(akka://deepdive)] DEBUG Executing SQL with callback... SELECT version() LIKE '%Postgres-XL%';
10:01:33 [PostgresDataStore(akka://deepdive)] DEBUG Executing query via JDBC: CREATE UNLOGGED TABLE dd_query_dd_new_has_spouse_0 AS SELECT R0.id AS "dd_new_has_spouse.R0.id" , R2.feature AS "has_spouse_features.R2.feature" FROM dd_new_has_spouse R0, dd_delta_has_spouse_candidates R1, has_spouse_features R2 WHERE R1.relation_id = R0.relation_id AND R2.relation_id = R0.relation_id UNION ALL SELECT R0.id AS "dd_new_has_spouse.R0.id" , R2.feature AS "dd_delta_has_spouse_features.R2.feature" FROM dd_new_has_spouse R0, dd_new_has_spouse_candidates R1, dd_delta_has_spouse_features R2 WHERE R1.relation_id = R0.relation_id AND R2.relation_id = R0.relation_id
10:01:33 [PostgresDataStore(akka://deepdive)] ERROR org.postgresql.util.PSQLException: ERROR: Failed to COMMIT the transaction on one or more nodes
10:01:33 [profiler] DEBUG ending report_id=inference_grounding
10:01:33 [taskManager] INFO  Completed task_id=inference_grounding with Failure(org.postgresql.util.PSQLException: ERROR: Failed to COMMIT the transaction on one or more nodes)
10:01:33 [taskManager] ERROR task=inference_grounding Failed: org.postgresql.util.PSQLException: ERROR: Failed to COMMIT the transaction on one or more nodes
10:01:33 [taskManager] ERROR Forcing shutdown
10:01:33 [taskManager] ERROR Cancelling task=calibration
10:01:33 [taskManager] ERROR Cancelling task=inference
/home/ubuntu/deepdive.xl/sbt/sbt: line 1:  6461 Killed                  java $SBT_OPTS -jar `dirname $0`/sbt-launch.jar "$@"
make: *** [test] Error 137
```

**Comment by SenWu** [comment]
For the record, Raphael passed all tests on PGXL in develop_fix branch. No "ERROR: Failed to COMMIT the transaction on one or more nodes" this time.

**Comment by netj** [comment]
@SenWu @raphaelhoffmann Are you sure?  Do you see the incremental test ending with two `PASS` lines?  I can consistently reproduce the error.  I just started a new EC2 instance, installed PGXL with our installer, and ran `make test` to get the same error.

**Comment by raphaelhoffmann** [comment]
Really? I am pretty sure and I have one witness. You are on develop_fix, right?

**Comment by netj** [comment]
@raphaelhoffmann Yes, maybe my environment is somehow interfering?  I'd like to cross verify it's working.

**Comment by raphaelhoffmann** [comment]
Based on your error message, this might be relevant: alldefector figured
out why XL nodes sometimes get stuck and how to recover from that. I'm just
copy/pasting his message here:
=================
A hard lesson I've learned about PGXL is that we should avoid running any
DML / DDL using plpy.execute inside a UDF (the same is is probably true for
plpgsql). I did that; sometimes it works, and sometimes it fails and PGXL
enters a limbo state where you simply cannot drop a table even after
restarting all servers. The culprit turned out to be some orphan prepared
transactions on the data nodes locking certain tables to block anybody else
from grabbing exclusive locks (hence DROP TABLE hangs). I had to use
commands like these to fix the DB:

for p in 3001 3002 3003; do psql -p $p spouses -c 'select * from
pg_prepared_xacts'; done
for p in 3001 3002 3003; do psql -p $p spouses -c "rollback prepared
'_\$XC\$3220'"; done

Here is a related trick for releasing monitoring spurious locks:
http://stackoverflow.com/questions/1063043/how-to-release-possible-postgres-row-locks

Next time PGXL misbehaves, try those to salvage it.

**Comment by netj** [comment]
@raphaelhoffmann Thanks for the info.  Yes, this may be relevant.  One quirk I always observed was the first createdb for deepdive_test was always failing, and I had to restart the test.  On the second run, it appeared to be running fine, but there such issue might have been lingering to cause the transaction error in incremental tests.  I'll trust your test results and merge this.

**Pull request merged**
