### PR TITLE
adding distributed_by support from annotation in ddlog

### PR DESCRIPTION
**Pull request by ThomasPalomares**
adding distributed_by support from annotation in ddlog

### CODE REVIEW

**Comment by netj** [comment]
Thanks for adding this feature!  Can you do a `make checkstyle` and also rebase to the latest branch in addition to my inline comments?

**Comment by netj** [comment]
@ThomasPalomares Please rebase onto 959282f11c6265c8f85ea9327eba9d0b85f46408 as the latest commit does not fully pass the test yet.  Sorry!

**Comment by ThomasPalomares** [comment]
Ahah sure. Also, concerning your previous comments, I added comments near the beginning and checked the trail spaces with a make checkstyle. I am not sure about how to highlight the new part of the code though

**Comment by ThomasPalomares** [comment]
ok rebased to 959282f !

**Comment by netj** [comment]
LGTM

**Pull request merged**
